# Generated by Django 5.0.6 on 2024-06-27 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_lanzamiento', models.DateField()),
                ('genero', models.CharField(max_length=100)),
                ('numero_episodios', models.PositiveIntegerField()),
                ('duracion_episodio', models.PositiveIntegerField(help_text='Duración promedio de episodios en minutos')),
                ('creador', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='series_images/')),
                ('etiquetas', models.ManyToManyField(blank=True, related_name='series', to='Registro.etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('calificacion', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('etiquetas', models.ManyToManyField(blank=True, related_name='reseñas', to='Registro.etiqueta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='Registro.serie')),
            ],
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('numero_episodio', models.PositiveIntegerField()),
                ('fecha_emision', models.DateField()),
                ('duracion', models.PositiveIntegerField(help_text='Duración del episodio en minutos')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='Registro.serie')),
            ],
        ),
    ]
